language: ruby
rvm:
  - 2.2.0
cache: bundler
addons:
  postgresql: "9.3"
env:
  - DB=postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
